# Generated by Django 4.2.4 on 2023-08-24 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('not_disclosed', 'Rather not disclose')], max_length=15, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('current_job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('github_profile_url', models.URLField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('percent_profile_completed', models.IntegerField(default=0)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('looking_for_job', models.BooleanField(default=False)),
                ('share_profile_with_recruiter', models.BooleanField(default=False)),
                ('looking_for_freelancing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_preference', models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('any', 'Onsite or Remote')], max_length=15, null=True)),
                ('expected_salary', models.PositiveIntegerField(default=0)),
                ('out_of_country', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userjobsearch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
