# Generated by Django 4.2.4 on 2023-08-28 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('migpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=1024)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('job_role', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_round', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('job_description', models.CharField(blank=True, max_length=400, null=True)),
                ('subject', models.CharField(blank=True, max_length=40, null=True)),
                ('topic', models.CharField(blank=True, max_length=40, null=True)),
                ('tools', models.CharField(blank=True, help_text='Put a comma after each tool', max_length=500, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('coding', 'Coding'), ('theory', 'Theory'), ('behavioural', 'Behavioural'), ('puzzle', 'Puzzle'), ('design', 'Design')], max_length=12, null=True)),
                ('user_instructions', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Put a comma after each tag', max_length=500, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userjobsearch',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('any', 'Onsite or Remote')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migpt.userinterview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
