# Generated by Django 4.2.4 on 2023-09-02 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0003_alter_userinterview_interview_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='is_asked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='job_role',
            field=models.CharField(default='SDE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='review',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
