# Generated by Django 4.2.4 on 2023-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0004_userquestionanswer_is_asked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
