# Generated by Django 4.2.4 on 2023-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0005_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='perfect_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='subject',
            field=models.CharField(blank=True, help_text='Put a comma after each subject', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='topic',
            field=models.CharField(blank=True, help_text='Put a comma after each topic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
