# Generated by Django 4.2.4 on 2023-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0006_userquestionanswer_improvements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='question_type',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('coding', 'Coding'), ('theory', 'Theory'), ('behavioural', 'Behavioural'), ('puzzle', 'Puzzle'), ('design', 'Design')], default='all', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='review',
            field=models.TextField(max_length=1024),
        ),
    ]
