# Generated by Django 4.2.4 on 2023-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0007_alter_userinterview_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='improvements',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='is_selected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='strong_points',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='weak_points',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
