# Generated by Django 4.2.4 on 2023-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0008_userinterview_improvements_userinterview_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='reason_selection',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
