# Generated by Django 4.2.4 on 2023-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0009_userinterview_reason_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='review',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
