# Generated by Django 4.2.4 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0010_alter_userinterview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='job_role',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='subject',
            field=models.CharField(blank=True, help_text='Put a comma after each subject', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='tools',
            field=models.CharField(blank=True, help_text='Put a comma after each tool', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='topic',
            field=models.CharField(blank=True, help_text='Put a comma after each topic', max_length=128, null=True),
        ),
    ]
