# Generated by Django 4.2.4 on 2023-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0011_alter_userinterview_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='job_description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
