# Generated by Django 4.2.4 on 2023-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0012_alter_userinterview_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='cross_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
