# Generated by Django 4.2.4 on 2023-09-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0013_userinterview_cross_question_userquestionanswer_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='pos',
            field=models.FloatField(default=0.0),
        ),
    ]
