# Generated by Django 4.2.4 on 2023-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0014_alter_userquestionanswer_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='auto_answer',
            field=models.BooleanField(default=False, help_text='Automatically answers all question using chatgpt.'),
        ),
    ]
