# Generated by Django 4.2.4 on 2023-10-11 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0016_alter_userinterview_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 minutes'), (datetime.timedelta(seconds=3600), '1 hour'), (datetime.timedelta(seconds=5400), '1 hour 30 minutes'), (datetime.timedelta(seconds=7200), '2 hours')], default=datetime.timedelta(seconds=3600)),
        ),
    ]
