# Generated by Django 4.2.4 on 2023-10-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0017_alter_userinterview_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='cost_of_conduct',
            field=models.FloatField(default=0.0),
        ),
    ]
