# Generated by Django 4.2.4 on 2023-10-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0018_userinterview_cost_of_conduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterview',
            name='cost_of_conduct',
        ),
        migrations.AddField(
            model_name='userinterview',
            name='cost_answer_review',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='cost_question_generation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='cost_review',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 minutes'), (datetime.timedelta(seconds=3600), '1 hour')], default=datetime.timedelta(seconds=1800)),
        ),
    ]
