# Generated by Django 4.2.4 on 2023-10-19 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0019_remove_userinterview_cost_of_conduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 minutes')], default=datetime.timedelta(seconds=1800)),
        ),
    ]
