# Generated by Django 4.2.4 on 2023-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0020_alter_userinterview_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='review_generated',
            field=models.BooleanField(default=False),
        ),
    ]
