# Generated by Django 4.2.4 on 2023-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0021_userinterview_review_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterview',
            name='improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='reason_selection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='strong_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinterview',
            name='weak_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
