# Generated by Django 4.2.4 on 2023-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0022_alter_userinterview_improvements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
