# Generated by Django 4.2.4 on 2023-12-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0023_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
