# Generated by Django 4.2.4 on 2023-12-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0025_contactus_created_at_contactus_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_rating', models.CharField(choices=[('1', '😞'), ('2', '😐'), ('3', '😊'), ('4', '😃'), ('5', '😍')], max_length=1)),
                ('helpfulness_rating', models.CharField(choices=[('1', '😞'), ('2', '😐'), ('3', '😊'), ('4', '😃'), ('5', '😍')], max_length=1)),
                ('interface_rating', models.CharField(choices=[('1', '😞'), ('2', '😐'), ('3', '😊'), ('4', '😃'), ('5', '😍')], max_length=1)),
                ('reviewer_rating', models.CharField(choices=[('1', '😞'), ('2', '😐'), ('3', '😊'), ('4', '😃'), ('5', '😍')], max_length=1)),
                ('website_rating', models.CharField(choices=[('1', '😞'), ('2', '😐'), ('3', '😊'), ('4', '😃'), ('5', '😍')], max_length=1)),
                ('improvements', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
