# Generated by Django 4.2.4 on 2023-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0026_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='helpfulness_rating',
            field=models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='interface_rating',
            field=models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_rating',
            field=models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reviewer_rating',
            field=models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='website_rating',
            field=models.CharField(choices=[('1', 'Very Poor'), ('2', 'Poor'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1),
        ),
    ]
