# Generated by Django 4.2.4 on 2024-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migpt', '0027_alter_feedback_helpfulness_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterview',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinterview',
            name='error_present',
            field=models.BooleanField(default=False),
        ),
    ]
